use_frameworks!

target 'ProtobufEX_Example' do
  pod 'ProtobufEX', :path => '../'
  pod 'Protobuf', '~> 3.1.0'

  target 'ProtobufEX_Tests' do
    inherit! :search_paths
    pod 'Protobuf', '~> 3.1.0'

  end
end
